// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiM_Q2DemTqnMjFYaEmJ1LvCa0S5g01SA',
    appId: '1:546854519359:web:5158c048a7be64c1ddee8a',
    messagingSenderId: '546854519359',
    projectId: 'restrauntappecell',
    authDomain: 'restrauntappecell.firebaseapp.com',
    storageBucket: 'restrauntappecell.firebasestorage.app',
    measurementId: 'G-WWDXLRWZCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkYmRCNkwQ7C7AOKksB6pslF0LtWeewQ',
    appId: '1:546854519359:android:f5f942f43a0581c9ddee8a',
    messagingSenderId: '546854519359',
    projectId: 'restrauntappecell',
    storageBucket: 'restrauntappecell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWfL_4Cjc5lS9gW3ntfWXQIgD65bA65Cc',
    appId: '1:546854519359:ios:441c0ed793c10d09ddee8a',
    messagingSenderId: '546854519359',
    projectId: 'restrauntappecell',
    storageBucket: 'restrauntappecell.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );
}
